name: Fetch Res

on:
  workflow_dispatch: ~

jobs:
  Fetch-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          tree -H '.' > sitemap.html
          uv sync --all-extras

      - name: Restore Old Files
        run: |
          mkdir -p data/raw
          mkdir -p tmp
          wget -q ${{ secrets.PUBLIC_URL }} -O genshin.zip
          unzip -q genshin.zip -d data/raw
          rm -rf genshin.zip

      - name: Fetch Remote Files
        run: |
          uv run _main.py

      - name: Zip Data
        run: |
          cd data/raw
          zip -q -r genshin.zip *
          mv genshin.zip ../../tmp/genshin.zip
          cd ../..
          rm -rf data/raw/genshin/other/data/Text*.json
          mv data tmp_data/data

      - name: Generate sitemap html
        run: |
          cd tmp_data
          tree -H '.' > sitemap.html
          cd ..

      - name: sync pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy tmp_data --project-name=paigram
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: sync r2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: 'auto'
          SOURCE_DIR: 'tmp'
